version: "3.7"
services:
  app:
    build:
      args:
        user: wilzzadex
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: digikas-app
    container_name: digikas-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - digikas-app

  nginx:
    image: nginx:alpine
    container_name: digikas-app-nginx
    restart: unless-stopped
    ports:
      - 8092:80
    volumes:
      - ./:/var/www
      - ./nginx:/etc/nginx/conf.d/
    networks:
      - digikas-app

networks:
  digikas-app:
    driver: bridge
